### ISSUE TITLE
Error: undefined method present?' for []:Array (NoMethodError)

### ISSUE THREAD

**Issue by erikpaasonen** [willbryant/parallel_rspec#8] opened 2023-06-27 15:59 UTC
hello! I'm trying to use this gem in a Ruby 3 environment, but it fails:
![image](https://github.com/willbryant/parallel_rspec/assets/17558034/329fb6b7-e9ba-4979-8bce-490d325d2333)

tried both Linux and MacOS environments, Ruby 3.0.0 and Ruby 3.2.2.

> Finished in 0.02066 seconds (files took 12.07 seconds to load)
> 0 examples, 0 failures
> 
> Randomized with seed 57038
> 
> bundler: failed to load command: prspec (/usr/local/lib/ruby/gems/3.2.0/bin/prspec)
/usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:9:in `block in any_context_hooks?': undefined method `present?' for []:Array (NoMethodError)
> 
>           group.hooks.send(:matching_hooks_for, :before, :context, group).present? ||
>                                                                          ^^^^^^^^^
> Did you mean?  prepend
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:8:in 'any?'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:8:in 'any_context_hooks?'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:63:in 'each'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:63:in 'partition'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:63:in 'block (2 levels) in run_specs'
	from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in 'with_suite_hooks'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:62:in 'block in run_specs'
	from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in 'report'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:61:in 'run_specs'
	from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in 'run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:51:in 'run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/lib/parallel_rspec/runner.rb:28:in 'invoke'
	from /usr/local/lib/ruby/gems/3.2.0/gems/parallel_rspec-2.1.1/exe/prspec:3:in '<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in 'load'
	from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in '<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in 'load'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in 'kernel_load'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in 'run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in 'exec'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in 'dispatch'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in 'start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:37:in 'block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in 'with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:29:in '<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:25:in 'load'
	from /usr/local/opt/ruby/bin/bundle:25:in '\<main\>'

**Comment by erikpaasonen** [comment] 2023-06-27 20:28
I tried to take a stab at [what appears to be the simple fix](https://github.com/erikpaasonen/parallel_rspec/blob/issue8/lib/parallel_rspec/runner.rb#L9-L10), but I'm encountering two problems:

1. (occasional/intermittent) during a `bundle exec prspec` run, one channel sometimes appears to return an empty response or something.
2. (consistently every time)  `bundle exec prspec` always errors out.

since I've never gotten this gem working, not sure whether these belong in distinct issues, so please let me know if I should file new ones for either/both of these.

error message blob for the first one:
```
/Users/user/forks/parallel_rspec/lib/parallel_rspec/channel.rb:46:in `dump': can't dump anonymous class #<Class:0x00000001108fdd40> (TypeError)

      encoded = Marshal.dump(data)
                             ^^^^
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/channel.rb:46:in `write'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/client.rb:30:in `example_finished'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:500:in `record_finished'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:483:in `finish'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:293:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:81:in `block in run_in_parallel'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:38:in `block (2 levels) in run_test_workers_with_server'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:30:in `fork'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:30:in `block in run_test_workers_with_server'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:27:in `each'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:27:in `collect'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:27:in `run_test_workers_with_server'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:74:in `run_in_parallel'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:64:in `block (2 levels) in run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:62:in `block in run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:61:in `run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:51:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:28:in `invoke'
        from /Users/user/forks/parallel_rspec/exe/prspec:3:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:29:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:25:in `load'
        from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
```
error message blob for the second one:
```
1 worker failed

bundler: failed to load command: prspec (/usr/local/lib/ruby/gems/3.2.0/bin/prspec)
/usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/notifications.rb:440:in `block in slowest_examples': undefined method `-@' for nil:NilClass (NoMethodError)

            -example.execution_result.run_time
            ^
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/notifications.rb:439:in `each'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/notifications.rb:439:in `sort_by'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/notifications.rb:439:in `slowest_examples'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/profile_formatter.rb:33:in `dump_profile_slowest_examples'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/profile_formatter.rb:26:in `dump_profile'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:209:in `block in notify'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:208:in `each'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:208:in `notify'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:181:in `block in finish'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:194:in `close_after'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:174:in `finish'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:76:in `ensure in report'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:76:in `report'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:61:in `run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:51:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:28:in `invoke'
        from /Users/user/forks/parallel_rspec/exe/prspec:3:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:29:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:25:in `load'
        from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
/Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:83:in `exit': exit (SystemExit)
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:83:in `verify_children'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/workers.rb:47:in `run_test_workers_with_server'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:74:in `run_in_parallel'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:64:in `block (2 levels) in run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:62:in `block in run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:61:in `run_specs'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:51:in `run'
        from /Users/user/forks/parallel_rspec/lib/parallel_rspec/runner.rb:28:in `invoke'
        from /Users/user/forks/parallel_rspec/exe/prspec:3:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/bin/prspec:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.14/exe/bundle:29:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:25:in `load'
        from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
```

I can't seem to stop Rspec itself from generating the profile in the first place. was hoping that would skirt around the second issue (the one that's a hard blocker).

I need to go through a process to get organizational permission to contribute to this repo, so posting this here in case someone wants to pick this up and drive a PR to get this working in the meantime.

**Comment by willbryant** [comment] 2023-06-28 00:33
Are you able to share your Gemfile & Gemfile.lock or do they have sensitive stuff in them?

**Comment by erikpaasonen** [comment] 2023-06-28 12:52
sure:
```
source 'https://rubygems.org'

gem 'aws-sdk-cloudwatchevents'
gem 'aws-sdk-cloudwatchlogs'
gem 'aws-sdk-codebuild'
gem 'aws-sdk-codepipeline'
gem 'aws-sdk-dynamodb'
gem 'aws-sdk-ecr'
gem 'aws-sdk-iam'
gem 'aws-sdk-glue'
gem 'aws-sdk-lambda'
gem 'aws-sdk-organizations'
gem 'aws-sdk-resourcegroups'
gem 'aws-sdk-s3'
gem 'aws-sdk-sqs'
gem 'aws-sdk-sns'
gem 'aws-sdk-ssm'
gem 'aws-sdk-states'
gem 'aws-sdk-sts'
gem 'iniparse'
gem 'jmespath', '~> 1.6.1'
gem 'jsonl'
gem 'pry'
gem 'rexml'
gem 'rspec'
gem 'rspec-repeat'
gem 'rspec-wait'
gem 'slop'
gem 'pager_duty-connection'
```

**Comment by erikpaasonen** [comment] 2023-06-28 12:52
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.0.4.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    aws-eventstream (1.2.0)
    aws-partitions (1.751.0)
    aws-sdk-cloudwatchevents (1.59.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-cloudwatchlogs (1.62.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-codebuild (1.90.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-codepipeline (1.55.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-core (3.171.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-dynamodb (1.84.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-ecr (1.58.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-glue (1.134.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-iam (1.77.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.63.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-lambda (1.95.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-organizations (1.74.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-resourcegroups (1.48.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.121.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sdk-sns (1.60.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sqs (1.53.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-ssm (1.150.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-states (1.52.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sts (1.9.0)
      aws-sdk-core (~> 3, >= 3.110.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.5.2)
      aws-eventstream (~> 1, >= 1.0.2)
    coderay (1.1.3)
    concurrent-ruby (1.2.2)
    diff-lcs (1.5.0)
    faraday (1.10.3)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    hashie (5.0.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    iniparse (1.5.0)
    jmespath (1.6.2)
    jsonl (0.1.5)
    method_source (1.0.0)
    minitest (5.18.0)
    multipart-post (2.3.0)
    pager_duty-connection (2.1.0)
      activesupport (>= 3.2, < 8.0)
      faraday (~> 1.0)
      faraday_middleware (~> 1.0)
      hashie (>= 1.2)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    rexml (3.2.5)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
      rspec-expectations (~> 3.12.0)
      rspec-mocks (~> 3.12.0)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-repeat (1.0.2)
      rspec (~> 3.0)
    rspec-support (3.12.0)
    rspec-wait (0.0.9)
      rspec (>= 3, < 4)
    ruby2_keywords (0.0.5)
    slop (4.10.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)

PLATFORMS
  arm64-darwin-21
  arm64-darwin-22
  x86_64-darwin-21
  x86_64-darwin-22
  x86_64-linux

DEPENDENCIES
  aws-sdk-cloudwatchevents
  aws-sdk-cloudwatchlogs
  aws-sdk-codebuild
  aws-sdk-codepipeline
  aws-sdk-dynamodb
  aws-sdk-ecr
  aws-sdk-glue
  aws-sdk-iam
  aws-sdk-lambda
  aws-sdk-organizations
  aws-sdk-resourcegroups
  aws-sdk-s3
  aws-sdk-sns
  aws-sdk-sqs
  aws-sdk-ssm
  aws-sdk-states
  aws-sdk-sts
  iniparse
  jmespath (~> 1.6.1)
  jsonl
  pager_duty-connection
  pry
  rexml
  rspec
  rspec-repeat
  rspec-wait
  slop

BUNDLED WITH
   2.4.14
```

**Comment by willbryant** [comment] 2023-07-02 10:13
Thanks.

I'm working on the second one at the moment, it's being caused by `--profile`, which is running into the way that I am reporting the example result back to the reporter on the server side, but not updating the original copy of the example which the profile code will  later on look at. Should be fixable by matching them up and writing the execution result back into it.

**Comment by willbryant** [comment] 2023-07-02 10:23
And I've merged and released your commit for the present? thing, meanwhile.

**Comment by willbryant** [comment] 2023-07-02 11:51
@erikpaasonen Please retest with 2.2.0. It should fix the original issue and the `-example.execution_result.run_time` issue. It may or may not fix the other issue - but if not could you please open a new issue for that?

**Comment by willbryant** [comment] 2023-07-07 09:46
Think I've probably figured out what the other issue was too. Will include a workaround in 2.4.0.

**Closed** 2023-07-07 09:46 UTC
